version: '3.9'
services:
  static:
    build:
      context: .
    image: speech-tts
    container_name: speech
    ports:
      - "5005:5005"
    networks: 
      - nginx-network

    version: '3.9'
      
networks: 
  nginx-network:
    name: nginx-network
    driver: bridge
    external: true