version: '3.9'
services:
  app:
    build:
      context: .
    image: speech-util
    container_name: speech
    environment:
      MODE: production
      PORT: 5005
    networks: 
      - nginx-network
      
networks: 
  nginx-network:
    name: nginx-network
    driver: bridge
    external: true